# Generated by Django 3.2.7 on 2021-09-11 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Should be phone number not back account number as mobile money is being used', max_length=128, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('district', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('subcounty', models.CharField(max_length=250)),
                ('village', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
