# Generated by Django 3.2.7 on 2021-09-12 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_alter_community_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='subcounty',
        ),
        migrations.AddField(
            model_name='community',
            name='sub_county',
            field=models.CharField(default='kazo', help_text='Sub county from which the community spans', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='community',
            name='about',
            field=models.TextField(help_text='Write something about this community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='country',
            field=models.CharField(default='Uganda', help_text='Country in which this community is found', max_length=250),
        ),
        migrations.AlterField(
            model_name='community',
            name='district',
            field=models.CharField(help_text='The district from which this community is found.', max_length=250),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Members of the community', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(help_text="Community's unique, it must be unique.", max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='village',
            field=models.CharField(help_text='The village the community will span', max_length=250),
        ),
    ]
