# Generated by Django 3.2.7 on 2021-09-17 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_auto_20210912_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentout',
            name='units',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='PayIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=15, null=True)),
                ('tx_ref', models.CharField(blank=True, max_length=100)),
                ('flw_ref', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=10)),
                ('units', models.IntegerField(default=0)),
                ('pay_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innitiator', to=settings.AUTH_USER_MODEL)),
                ('pay_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
