# Generated by Django 3.2.7 on 2021-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20210917_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_number',
            field=models.CharField(blank=True, help_text='Should be phone number not back account number as mobile money is being used', max_length=14, null=True, verbose_name='Phone number'),
        ),
    ]
